In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

# 원본 결과 (tally에서 다운받은것)
# '/content/drive/MyDrive/졸업프로젝트/설문결과/Survey_Submissions_2024-10-13.csv'

# 원본 결과 전처리 한거
survey_result_preprocessed = pd.read_csv('/content/drive/MyDrive/졸업프로젝트/설문결과/survey_result_preprocessed.csv',encoding='utf-8',index_col=0)

# 원본 결과 중 모델링이랑 관련 없는 변수 설문 결과 정리한거
survey_etc = pd.read_csv('/content/drive/MyDrive/졸업프로젝트/설문결과/survey_etc.csv',encoding='utf-8',index_col=0)

In [3]:
# 응답자 203명, 응답자별로 답변 8개 = 총 1632rows
# 우리 설문구성한대로 attribute left join 해줌 (survey_block, run 기준으로)
survey_result_preprocessed

,ID,survey_block,route_choice,male,age,income,run,A_ovt_fmlm,A_ivt,A_ovt_transfer,A_cost,B_ovt_fmlm,B_ivt,B_ovt_transfer,B_cost
0,0,4,경로 A,True,40세 이상,500만원 이상,1,10,50,10,1500,14,50,10,1750
1,0,4,경로 B,True,40세 이상,500만원 이상,2,16,35,8,2250,10,45,6,2000
2,0,4,경로 B,True,40세 이상,500만원 이상,3,14,40,6,2000,16,40,8,1500
3,0,4,경로 B,True,40세 이상,500만원 이상,4,14,45,8,1500,16,35,6,1750
4,0,4,경로 B,True,40세 이상,500만원 이상,5,12,40,10,2250,12,40,10,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1627,203,1,경로 B,False,20세 이상 24세 이하,100 ~ 200만원,4,12,45,6,2000,10,45,10,1750
1628,203,1,경로 A,False,20세 이상 24세 이하,100 ~ 200만원,5,16,40,10,1750,16,45,12,1750
1629,203,1,경로 B,False,20세 이상 24세 이하,100 ~ 200만원,6,14,35,12,1500,10,40,10,2250
1630,203,1,경로 A,False,20세 이상 24세 이하,100 ~ 200만원,7,10,45,8,2000,12,50,8,2000
1631,203,1,경로 A,False,20세 이상 24세 이하,100 ~ 200만원,8,10,50,8,2250,16,40,12,2250

In [4]:
survey_etc

,birth_month,gender,age,income,commonly_used_vehicle,service_difficulty,phone_number
0,"10, 11, 12월",남,40세 이상,500만원 이상,"대중교통 (버스, 철도)",불편한 점이 없다.,01020611095
1,"7, 8, 9월",여,40세 이상,300 ~ 500만원,승용차,NaN,01041633771
2,"1, 2, 3월",남,40세 이상,500만원 이상,"대중교통 (버스, 철도)","추천 경로가 사용자의 개별 선호나 습관을 반영하지 않고, 모든 사용자에게 동일한 형...",01042231190
3,"7, 8, 9월",여,40세 이상,500만원 이상,"대중교통 (버스, 철도)","추천 경로가 사용자의 개별 선호나 습관을 반영하지 않고, 모든 사용자에게 동일한 형...",NaN
4,"1, 2, 3월",여,40세 이상,500만원 이상,"대중교통 (버스, 철도)",제시해주는 경로가 최적경로가 아닌 것 같다.,01031251312
...,...,...,...,...,...,...,...
199,"4, 5, 6월",여,20세 이상 24세 이하,100 ~ 200만원,"대중교통 (버스, 철도)","추천 경로가 사용자의 개별 선호나 습관을 반영하지 않고, 모든 사용자에게 동일한 형...",01039043160
200,"7, 8, 9월",여,20세 이상 24세 이하,50 ~ 100만원,"대중교통 (버스, 철도)","추천 경로가 사용자의 개별 선호나 습관을 반영하지 않고, 모든 사용자에게 동일한 형...",01083570718
201,"1, 2, 3월",여,20세 이상 24세 이하,100 ~ 200만원,"대중교통 (버스, 철도)","추천 경로가 사용자의 개별 선호나 습관을 반영하지 않고, 모든 사용자에게 동일한 형...",01036690534
202,"1, 2, 3월",여,20세 이상 24세 이하,100 ~ 200만원,"대중교통 (버스, 철도)",제시해주는 예상 소요 시간이 정확하지 않다.,01024190329
203,"1, 2, 3월",여,20세 이상 24세 이하,100 ~ 200만원,"대중교통 (버스, 철도)",제시해주는 경로가 최적경로가 아닌 것 같다.,NaN

In [5]:
# 기초 통계
survey_etc['birth_month'].value_counts()

birth_month
10, 11, 12월    57
1, 2, 3월       55
4, 5, 6월       53
7, 8, 9월       39
Name: count, dtype: int64

In [6]:
survey_etc['gender'].value_counts()

gender
남    110
여     94
Name: count, dtype: int64

In [7]:
survey_etc['age'].value_counts()

age
20세 이상 24세 이하    86
40세 이상           63
25세 이상 29세 이하    39
30세 이상 34세 이하    10
35세 이상 39세 이하     6
Name: count, dtype: int64

In [8]:
survey_etc['income'].value_counts()

income
500만원 이상       52
50만원 이하        36
100 ~ 200만원    34
50 ~ 100만원     33
300 ~ 500만원    30
200 ~ 300만원    19
Name: count, dtype: int64

In [9]:
survey_etc['commonly_used_vehicle'].value_counts()

commonly_used_vehicle
대중교통 (버스, 철도)       158
승용차                  40
도보                    3
자전거, 전동킥보드, 오토바이      2
대중교통                  1
Name: count, dtype: int64

In [10]:
survey_etc['service_difficulty'].value_counts()

service_difficulty
추천 경로가 사용자의 개별 선호나 습관을 반영하지 않고, 모든 사용자에게 동일한 형식으로 제공된다.                                                61
제시해주는 경로가 최적경로가 아닌 것 같다.                                                                               43
제시해주는 예상 소요 시간이 정확하지 않다.                                                                               27
불편한 점이 없다.                                                                                             22
불편한 점이 없다기 보단 평소에 고민해 본적이 없어서 뭐가 불편한지 인식을 못하겠어요                                                         1
도보에 오르막길이 적용되지 않음                                                                                       1
한 정류장에서 탑승하고 같거나 근처 정류장에서 내릴 수 있는 버스 노선이 여러개인데, 지선/간선/광역에 따라 다른 경로로 구분해버려서 버스 도착시간을 일일이 파악해야해서 불편하다     1
대기시간이 제대로 고려되지 않는 것 같아서 불편하다                                                                            1
배차시간(차량 대기시간)도 반영해서 예상 도착(소요)시간을 알려주면 조을 것 가타요 지원언니화이팅                                                  1
Name: count, dtype: int64

## 추첨

In [17]:
survey_etc['phone_number'].sample(n=5)

64     01028839390
137    01090278595
178    01064711021
56     01086002176
200    01083570718
Name: phone_number, dtype: object